/**
 * impress.js
 *
 * impress.js is a presentation tool based on the power of CSS3 transforms and transitions
 * in modern browsers and inspired by the idea behind prezi.com.
 *
 *
 * Copyright 2011-2012 Bartek Szopka (@bartaz)
 *
 * Released under the MIT and GPL Licenses.
 *
 * ------------------------------------------------
 *  author:  Bartek Szopka
 *  version: 0.5.3
 *  url:     http://bartaz.github.com/impress.js/
 *  source:  http://github.com/bartaz/impress.js/
 */
(function(d,h){var n,r=d.createElement("dummy").style,j=["Webkit","Moz","O","ms","Khtml"],a={};n=function(g){if("undefined"===typeof a[g]){var t=g.charAt(0).toUpperCase()+g.substr(1),t=(g+" "+j.join(t+" ")+t).split(" ");a[g]=null;for(var b in t)if(void 0!==r[t[b]]){a[g]=t[b];break}}return a[g]};var b=function(g,a){var b,e;for(b in a)a.hasOwnProperty(b)&&(e=n(b),null!==e&&(g.style[e]=a[b]));return g},e=function(g,a){return isNaN(g)?a||0:Number(g)},v=function(g){return d.getElementById(g)},y=function(g,
a,b){var e=d.createEvent("CustomEvent");e.initCustomEvent(a,!0,!0,b);g.dispatchEvent(e)},C=function(g){return" translate3d("+g.x+"px,"+g.y+"px,"+g.z+"px) "},D=function(g,a){var b=" rotateX("+g.x+"deg) ",e=" rotateY("+g.y+"deg) ",d=" rotateZ("+g.z+"deg) ";return a?d+e+b:b+e+d},E=function(a){var b=h.innerHeight/a.height,e=h.innerWidth/a.width,b=b>e?e:b;a.maxScale&&b>a.maxScale&&(b=a.maxScale);a.minScale&&b<a.minScale&&(b=a.minScale);return b},m=d.body,z=navigator.userAgent.toLowerCase(),A=null!==n("perspective")&&
m.classList&&m.dataset&&-1===z.search(/(iphone)|(ipod)|(android)/);A?(m.classList.remove("impress-not-supported"),m.classList.add("impress-supported")):m.className+=" impress-not-supported ";var s={},w=function(){return!1};(h.impress=function(a){if(!A)return{init:w,gotoer:w,prev:w,next:w};a=a||"impress";if(s["impress-root-"+a])return s["impress-root-"+a];var j={},l=null,p=null,i=null,u=null,n=null,k=v(a),r=d.createElement("div"),B=!1,x=null,z=function(f,a){var c=f.dataset,c={translate:{x:e(c.x),y:e(c.y),
z:e(c.z)},rotate:{x:e(c.rotateX),y:e(c.rotateY),z:e(c.rotateZ||c.rotate)},scale:e(c.scale,1),el:f};f.id||(f.id="step-"+(a+1));j["impress-"+f.id]=c;b(f,{position:"absolute",transform:"translate(-50%,-50%)"+C(c.translate)+D(c.rotate)+(" scale("+c.scale+") "),transformStyle:"preserve-3d"})},F=null,q=function(a,d){var c;if(!(c=!B))c=a,"number"===typeof c?c=0>c?i[i.length+c]:i[c]:"string"===typeof c&&(c=v(c)),c=!(a=c&&c.id&&j["impress-"+c.id]?c:null);if(c)return!1;h.scrollTo(0,0);c=j["impress-"+a.id];
l&&(l.classList.remove("active"),m.classList.remove("impress-on-"+l.id));a.classList.add("active");m.classList.add("impress-on-"+a.id);c={rotate:{x:-c.rotate.x,y:-c.rotate.y,z:-c.rotate.z},translate:{x:-c.translate.x,y:-c.translate.y,z:-c.translate.z},scale:1/c.scale};var g=c.scale>=p.scale,d=e(d,u.transitionDuration),q=d/2;a===l&&(n=E(u));var s=c.scale*n;l&&l!==a&&x===l&&(y(l,"impress:stepleave"),x=null);b(k,{transform:" perspective("+u.perspective/s+"px) "+(" scale("+s+") "),transitionDuration:d+
"ms",transitionDelay:(g?q:0)+"ms"});b(r,{transform:D(c.rotate,!0)+C(c.translate),transitionDuration:d+"ms",transitionDelay:(g?0:q)+"ms"});if(p.scale===c.scale||p.rotate.x===c.rotate.x&&p.rotate.y===c.rotate.y&&p.rotate.z===c.rotate.z&&p.translate.x===c.translate.x&&p.translate.y===c.translate.y&&p.translate.z===c.translate.z)q=0;p=c;l=a;h.clearTimeout(F);F=h.setTimeout(function(){var a=l;x!==a&&(y(a,"impress:stepenter"),x=a)},d+q);return a};k.addEventListener("impress:init",function(){i.forEach(function(a){a.classList.add("future")});
k.addEventListener("impress:stepenter",function(a){a.target.classList.remove("past");a.target.classList.remove("future");a.target.classList.add("present")},!1);k.addEventListener("impress:stepleave",function(a){a.target.classList.remove("present");a.target.classList.add("past")},!1)},!1);k.addEventListener("impress:init",function(){var a="";k.addEventListener("impress:stepenter",function(b){h.location.hash=a="#/"+b.target.id},!1);h.addEventListener("hashchange",function(){h.location.hash!==a&&q(v(h.location.hash.replace(/^#\/?/,
"")))},!1);q(v(h.location.hash.replace(/^#\/?/,""))||i[0],0)},!1);m.classList.add("impress-disabled");return s["impress-root-"+a]={init:function(){if(!B){var f;f=d;f=f.querySelector("meta[name='viewport']")||d.createElement("meta");f.content="width=device-width, minimum-scale=1, maximum-scale=1, user-scalable=no";f.parentNode!==d.head&&(f.name="viewport",d.head.appendChild(f));f=k.dataset;u={width:e(f.width,1024),height:e(f.height,768),maxScale:e(f.maxScale,1),minScale:e(f.minScale,0),perspective:e(f.perspective,
1E3),transitionDuration:e(f.transitionDuration,1E3)};n=E(u);[].slice.call(k.childNodes).forEach(function(a){r.appendChild(a)});k.appendChild(r);d.documentElement.style.height="100%";b(m,{height:"100%",overflow:"hidden"});f={position:"absolute",transformOrigin:"top left",transition:"all 0s ease-in-out",transformStyle:"preserve-3d"};b(k,f);b(k,{top:"50%",left:"50%",transform:" perspective("+u.perspective/n+"px) "+(" scale("+n+") ")});b(r,f);m.classList.remove("impress-disabled");m.classList.add("impress-enabled");
f=(f=k)||d;f=f.querySelectorAll(".step");i=[].slice.call(f);i.forEach(z);p={translate:{x:0,y:0,z:0},rotate:{x:0,y:0,z:0},scale:1};B=!0;y(k,"impress:init",{api:s["impress-root-"+a]})}},gotoer:q,next:function(){var a=i.indexOf(l)+1,a=a<i.length?i[a]:i[0];return q(a)},prev:function(){var a=i.indexOf(l)-1,a=0<=a?i[a]:i[i.length-1];return q(a)}}}).supported=A})(document,window);
(function(d,h){var n=function(d,h){var a=null;return function(){var b=this,e=arguments;clearTimeout(a);a=setTimeout(function(){d.apply(b,e)},h)}};d.addEventListener("impress:init",function(r){var j=r.detail.api;d.addEventListener("keydown",function(a){(9===a.keyCode||32<=a.keyCode&&34>=a.keyCode||37<=a.keyCode&&40>=a.keyCode)&&a.preventDefault()},!1);d.addEventListener("keyup",function(a){if(9===a.keyCode||32<=a.keyCode&&34>=a.keyCode||37<=a.keyCode&&40>=a.keyCode){switch(a.keyCode){case 33:case 37:case 38:j.prev();
break;case 9:case 32:case 34:case 39:case 40:j.next()}a.preventDefault()}},!1);d.addEventListener("click",function(a){for(var b=a.target;"A"!==b.tagName&&b!==d.documentElement;)b=b.parentNode;if("A"===b.tagName){var e=b.getAttribute("href");e&&"#"===e[0]&&(b=d.getElementById(e.slice(1)))}j.gotoer(b)&&(a.stopImmediatePropagation(),a.preventDefault())},!1);d.addEventListener("click",function(a){for(var b=a.target;(!b.classList.contains("step")||b.classList.contains("active"))&&b!==d.documentElement;)b=
b.parentNode;j.gotoer(b)&&a.preventDefault()},!1);d.addEventListener("touchstart",function(a){if(1===a.touches.length){var b=a.touches[0].clientX,e=0.3*h.innerWidth,d=null;b<e?d=j.prev():b>h.innerWidth-e&&(d=j.next());d&&a.preventDefault()}},!1);h.addEventListener("resize",n(function(){j.gotoer(d.querySelector(".active"),500)},250),!1)},!1)})(document,window);
